"""
Verbatim re-emission of unedited entries (areyousievious-8fg.14).

Opening a Roundcube- or SOGo-authored script and editing one Rule used to
rewrite EVERY Rule into our house style. The file is now a sequence of
spans: parse records the bytes each entry came from, and the generator
re-emits that span byte-identical unless the entry has actually changed.

Run from the backend/ directory:
    cd backend && python -m pytest tests/test_verbatim_reemission.py -v
"""

from __future__ import annotations

from pathlib import Path

import pytest
import sieve_transform as st


def test_new_entries_carry_an_empty_span():
    """A Rule the builder minted was never parsed from anything, so it has no
    span and must regenerate. `""` is that state — not None, so no caller has
    to reason about two kinds of absent."""
    assert st.Rule().source == ""
    assert st.RawBlock(text="keep;").source == ""


def test_a_fresh_script_has_no_preamble_requires_source_or_tail():
    script = st.SieveScript()
    assert script.preamble == ""
    assert script.requires_source == ""
    assert script.tail == ""


def test_spans_survive_the_json_round_trip():
    """The span crosses the wire and comes back. If `script_to_json` drops it,
    every save regenerates and the whole feature is silently inert."""
    script = st.SieveScript(
        requires=["fileinto"],
        entries=[st.Rule(name="Spam", source="# --- Spam ---\nif true {\n  keep;\n}\n")],
        preamble="# hand-written header\n",
        requires_source='require ["fileinto"];\n',
        tail="\n# trailing note\n",
    )
    back = st.json_to_script(st.script_to_json(script))
    assert back.preamble == script.preamble
    assert back.requires_source == script.requires_source
    assert back.tail == script.tail
    assert back.entries[0].source == script.entries[0].source


def test_raw_block_spans_survive_the_json_round_trip():
    script = st.SieveScript(entries=[st.RawBlock(text="keep;", source="\nkeep;\n")])
    back = st.json_to_script(st.script_to_json(script))
    assert back.entries[0].source == "\nkeep;\n"


BACKEND = Path(__file__).resolve().parent.parent

# The same corpus definition, filter included, as `test_sieve_transform.py`'s
# TEST_SCRIPTS. It excludes nothing today — there is no empty fixture — and it
# is kept only so the two suites are parametrized over provably the same set,
# which is what lets Task 5 lift ONE definition into a conftest fixture rather
# than reconcile two that had drifted. The empty file is a real case for this
# decomposition and is covered directly, by `test_an_empty_file_is_all_tail`,
# rather than by dropping the filter here and diverging.
FIXTURES = sorted(p for p in (BACKEND / "test_scripts").rglob("*.sieve") if p.stat().st_size > 0)


def _reassemble(script: st.SieveScript) -> str:
    return (
        script.preamble
        + script.requires_source
        + "".join(e.source for e in script.entries)
        + script.tail
    )


@pytest.mark.parametrize(
    "path", FIXTURES, ids=lambda p: str(p.relative_to(BACKEND / "test_scripts"))
)
def test_the_spans_reassemble_the_original_file(path: Path):
    """Every byte belongs to exactly one span.

    This is the load-bearing invariant. If a byte is in no span it is lost on
    save; if it is in two it is duplicated. Neither is visible in a test that
    only compares parsed structures, because both sides have already lost it.
    """
    text = path.read_text()
    assert _reassemble(st.parse_sieve(text)) == text


def test_a_rules_span_carries_the_comment_immediately_above_it():
    text = 'require ["fileinto"];\n\n# keep the receipts\n# --- Receipts ---\nif header :contains "subject" "receipt" {\n  fileinto "Receipts";\n}\n'
    script = st.parse_sieve(text)
    assert len(script.entries) == 1
    assert "# keep the receipts" in script.entries[0].source
    assert "# keep the receipts" not in script.preamble


def test_content_before_the_first_require_is_preamble():
    text = '# Generated by Roundcube\nrequire ["fileinto"];\n\nif true {\n  keep;\n}\n'
    script = st.parse_sieve(text)
    assert script.preamble == "# Generated by Roundcube\n"
    assert script.requires_source == 'require ["fileinto"];\n'


def test_an_unlexable_file_is_one_span_covering_everything():
    """The `usable == False` fallback returns the whole file as one RawBlock
    with its trailing newlines stripped from `text`. `source` must keep them,
    or the invariant fails on exactly the file we understand least."""
    text = "\x00 this is not sieve at all\n\n"
    script = st.parse_sieve(text)
    assert _reassemble(script) == text


# ── The tail term ──
#
# No fixture in the corpus produces a non-empty tail, so the parametrized
# invariant above never exercises the fourth term. Two mutations survived the
# whole file because of that: `script.tail = ""` at the end of `parse`, and the
# blank-and-unlexable branch returning `tail=""` instead of `tail=self.text`.
# Both are the "byte in no span, lost on save" case that test's own docstring
# names, so the tail gets hand-written coverage of its own.


def test_a_trailing_comment_and_blank_lines_are_tail():
    """Bytes after the last entry belong to no entry — they are not part of the
    rule above them, or reordering that rule would drag the file's sign-off
    along with it."""
    text = "if true {\n  keep;\n}\n\n# trailing note\n"
    script = st.parse_sieve(text)
    assert script.entries[0].source == "if true {\n  keep;\n}\n"
    assert script.tail == "\n# trailing note\n"
    assert _reassemble(script) == text


def test_a_file_of_nothing_but_blank_lines_is_all_tail():
    text = "\n\n\n"
    script = st.parse_sieve(text)
    assert script.entries == []
    assert script.tail == text
    assert _reassemble(script) == text


def test_an_empty_file_is_all_tail():
    """`""` in, `""` out. The degenerate end of the decomposition, and the case
    the `st_size > 0` filter on FIXTURES would otherwise leave unasserted."""
    script = st.parse_sieve("")
    assert script.entries == []
    assert _reassemble(script) == ""


def test_a_blank_unlexable_file_keeps_its_bytes_in_the_tail():
    """Whitespace-only AND refused by the Lexer, which is the one path that
    returns before the main loop with no entry to hang the bytes on. `\\xa0` is
    non-breaking space: `str.strip()` removes it, so `body.strip()` is falsy and
    this reaches the `tail=self.text` branch."""
    text = "\xa0"
    script = st.parse_sieve(text)
    assert script.entries == []
    assert script.tail == text
    assert _reassemble(script) == text


def test_a_require_after_an_entry_stays_where_it_was_written():
    """RFC 5228 §3.2 puts every `require` before every command, so this file is
    already invalid Sieve — but it reassembles or the invariant is not "for any
    text x". `requires_source` is concatenated ahead of every entry, so these
    bytes cannot go there: they would come back ABOVE the rule they follow."""
    text = 'if true {\n  keep;\n}\nrequire ["fileinto"];\n'
    script = st.parse_sieve(text)
    assert _reassemble(script) == text
    assert script.requires_source == ""
    assert isinstance(script.entries[1], st.RawBlock)
    # NOT harvested. The verbatim bytes still declare the extension; harvesting
    # would have a regenerating save emit a canonical `require` at the top too,
    # and the file would declare `fileinto` twice.
    assert script.requires == []
