"""
Verbatim re-emission of unedited entries (areyousievious-8fg.14).

Opening a Roundcube- or SOGo-authored script and editing one Rule used to
rewrite EVERY Rule into our house style. The file is now a sequence of
spans: parse records the bytes each entry came from, and the generator
re-emits that span byte-identical unless the entry has actually changed.

Run from the backend/ directory:
    cd backend && python -m pytest tests/test_verbatim_reemission.py -v
"""

from __future__ import annotations

from pathlib import Path

import pytest
import sieve_transform as st

from tests.conftest import CORPUS, corpus_id


def test_new_entries_carry_an_empty_span():
    """A Rule the builder minted was never parsed from anything, so it has no
    span and must regenerate. `""` is that state — not None, so no caller has
    to reason about two kinds of absent."""
    assert st.Rule().source == ""
    assert st.RawBlock(text="keep;").source == ""


def test_a_fresh_script_has_no_preamble_requires_source_or_tail():
    script = st.SieveScript()
    assert script.preamble == ""
    assert script.requires_source == ""
    assert script.tail == ""


def test_spans_survive_the_json_round_trip():
    """The span crosses the wire and comes back. If `script_to_json` drops it,
    every save regenerates and the whole feature is silently inert."""
    script = st.SieveScript(
        requires=["fileinto"],
        entries=[st.Rule(name="Spam", source="# --- Spam ---\nif true {\n  keep;\n}\n")],
        preamble="# hand-written header\n",
        requires_source='require ["fileinto"];\n',
        tail="\n# trailing note\n",
    )
    back = st.json_to_script(st.script_to_json(script))
    assert back.preamble == script.preamble
    assert back.requires_source == script.requires_source
    assert back.tail == script.tail
    assert back.entries[0].source == script.entries[0].source


def test_raw_block_spans_survive_the_json_round_trip():
    script = st.SieveScript(entries=[st.RawBlock(text="keep;", source="\nkeep;\n")])
    back = st.json_to_script(st.script_to_json(script))
    assert back.entries[0].source == "\nkeep;\n"


def _reassemble(script: st.SieveScript) -> str:
    return (
        script.preamble
        + script.requires_source
        + "".join(e.source for e in script.entries)
        + script.tail
    )


@pytest.mark.parametrize("path", CORPUS, ids=corpus_id)
def test_the_spans_reassemble_the_original_file(path: Path):
    """Every byte belongs to exactly one span.

    This is the load-bearing invariant. If a byte is in no span it is lost on
    save; if it is in two it is duplicated. Neither is visible in a test that
    only compares parsed structures, because both sides have already lost it.
    """
    text = path.read_text()
    assert _reassemble(st.parse_sieve(text)) == text


def test_a_rules_span_carries_the_comment_immediately_above_it():
    text = 'require ["fileinto"];\n\n# keep the receipts\n# --- Receipts ---\nif header :contains "subject" "receipt" {\n  fileinto "Receipts";\n}\n'
    script = st.parse_sieve(text)
    assert len(script.entries) == 1
    assert "# keep the receipts" in script.entries[0].source
    assert "# keep the receipts" not in script.preamble


def test_content_before_the_first_require_is_preamble():
    text = '# Generated by Roundcube\nrequire ["fileinto"];\n\nif true {\n  keep;\n}\n'
    script = st.parse_sieve(text)
    assert script.preamble == "# Generated by Roundcube\n"
    assert script.requires_source == 'require ["fileinto"];\n'


def test_an_unlexable_file_is_one_span_covering_everything():
    """The `usable == False` fallback returns the whole file as one RawBlock
    with its trailing newlines stripped from `text`. `source` must keep them,
    or the invariant fails on exactly the file we understand least."""
    text = "\x00 this is not sieve at all\n\n"
    script = st.parse_sieve(text)
    assert _reassemble(script) == text


# ── The tail term ──
#
# No fixture in the corpus produces a non-empty tail, so the parametrized
# invariant above never exercises the fourth term. Two mutations survived the
# whole file because of that: `script.tail = ""` at the end of `parse`, and the
# blank-and-unlexable branch returning `tail=""` instead of `tail=self.text`.
# Both are the "byte in no span, lost on save" case that test's own docstring
# names, so the tail gets hand-written coverage of its own.


def test_a_trailing_comment_and_blank_lines_are_tail():
    """Bytes after the last entry belong to no entry — they are not part of the
    rule above them, or reordering that rule would drag the file's sign-off
    along with it."""
    text = "if true {\n  keep;\n}\n\n# trailing note\n"
    script = st.parse_sieve(text)
    assert script.entries[0].source == "if true {\n  keep;\n}\n"
    assert script.tail == "\n# trailing note\n"
    assert _reassemble(script) == text


def test_a_file_of_nothing_but_blank_lines_is_all_tail():
    text = "\n\n\n"
    script = st.parse_sieve(text)
    assert script.entries == []
    assert script.tail == text
    assert _reassemble(script) == text


def test_an_empty_file_is_all_tail():
    """`""` in, `""` out. The degenerate end of the decomposition, and the case
    the `st_size > 0` filter on `CORPUS` would otherwise leave unasserted."""
    script = st.parse_sieve("")
    assert script.entries == []
    assert _reassemble(script) == ""


def test_a_blank_unlexable_file_keeps_its_bytes_in_the_tail():
    """Whitespace-only AND refused by the Lexer, which is the one path that
    returns before the main loop with no entry to hang the bytes on. `\\xa0` is
    non-breaking space: `str.strip()` removes it, so `body.strip()` is falsy and
    this reaches the `tail=self.text` branch."""
    text = "\xa0"
    script = st.parse_sieve(text)
    assert script.entries == []
    assert script.tail == text
    assert _reassemble(script) == text


def test_a_require_after_an_entry_stays_where_it_was_written():
    """RFC 5228 §3.2 puts every `require` before every command, so this file is
    already invalid Sieve — but it reassembles or the invariant is not "for any
    text x". `requires_source` is concatenated ahead of every entry, so these
    bytes cannot go there: they would come back ABOVE the rule they follow."""
    text = 'if true {\n  keep;\n}\nrequire ["fileinto"];\n'
    script = st.parse_sieve(text)
    assert _reassemble(script) == text
    assert script.requires_source == ""
    assert isinstance(script.entries[1], st.RawBlock)
    # NOT harvested. The verbatim bytes still declare the extension; harvesting
    # would have a regenerating save emit a canonical `require` at the top too,
    # and the file would declare `fileinto` twice.
    assert script.requires == []


_HOUSE_STYLE_IS_DIFFERENT = (
    'require ["fileinto"];\n'
    "\n"
    "# --- Receipts ---\n"
    'if anyof (header :contains "subject" "receipt")\n'
    "{\n"
    '\tfileinto "Receipts";\n'
    "}\n"
)


def test_an_untouched_rule_re_emits_byte_identical():
    """The brace on its own line and the tab indent are not our house style.
    Before spans, a save rewrote both. Now nothing changed, so nothing moves."""
    script = st.parse_sieve(_HOUSE_STYLE_IS_DIFFERENT)
    assert st.generate_sieve(script) == _HOUSE_STYLE_IS_DIFFERENT


def test_an_edited_rule_regenerates_and_its_neighbour_does_not():
    text = (
        'require ["fileinto"];\n'
        "\n"
        "# --- One ---\n"
        'if anyof (header :contains "subject" "one")\n'
        "{\n"
        '\tfileinto "One";\n'
        "}\n"
        "\n"
        "# --- Two ---\n"
        'if anyof (header :contains "subject" "two")\n'
        "{\n"
        '\tfileinto "Two";\n'
        "}\n"
    )
    script = st.parse_sieve(text)
    script.entries[1].actions[0].argument = "Elsewhere"
    out = st.generate_sieve(script)
    assert '\tfileinto "One";' in out, "the untouched rule kept its tab indent"
    assert '\tfileinto "Elsewhere";' not in out, "the edited rule is in house style"
    assert 'fileinto "Elsewhere";' in out


def test_a_reordered_rule_takes_its_name_line_with_it():
    text = "# --- Alpha ---\nif true {\n  keep;\n}\n\n# --- Beta ---\nif false {\n  discard;\n}\n"
    script = st.parse_sieve(text)
    script.entries.reverse()
    out = st.generate_sieve(script)
    assert out.index("# --- Beta ---") < out.index("# --- Alpha ---")
    assert out.index("# --- Beta ---") < out.index("discard;")


def test_an_over_declared_require_survives_an_untouched_save():
    """`_compute_requires` prunes on regeneration (areyousievious-8fg.15).
    Pruning an untouched file would rewrite a line we were not asked to touch,
    so it now happens only on a save that regenerates something."""
    text = 'require ["fileinto", "reject"];\n\nif true {\n  keep;\n}\n'
    assert st.generate_sieve(st.parse_sieve(text)) == text


def test_editing_a_rule_still_prunes_the_require():
    # A real test, not `if true`: `if true` has no recognisable test so it
    # parses to a RawBlock, and `_compute_requires` preserves the declared set
    # whole when any entry is a RawBlock — there would be nothing to prune.
    text = (
        'require ["fileinto", "reject"];\n'
        "\n"
        'if header :contains "subject" "box" {\n  fileinto "Box";\n}\n'
    )
    script = st.parse_sieve(text)
    script.entries[0].actions[0].argument = "Other"
    out = st.generate_sieve(script)
    assert '"reject"' not in out


def test_a_minted_rule_between_two_verbatim_ones_gets_one_blank_line_each_side():
    text = "if true {\n  keep;\n}\n\nif false {\n  discard;\n}\n"
    script = st.parse_sieve(text)
    script.entries.insert(
        1, st.Rule(name="New", conditions=[], actions=[st.Action(action_type="stop")])
    )
    out = st.generate_sieve(script)
    assert "\n\n\n" not in out, "no run of blank lines at a verbatim/regenerated seam"
    assert "}\nif" not in out, "entries are still separated"


def test_generation_scales_linearly_in_the_number_of_entries():
    """Not a benchmark — a shape check. 400 entries must not cost ~16x what
    100 does. The disabled-block retry path was O(n^2) for exactly this
    reason and 800 fragments took 1.5s on a request that admits 1 MiB."""
    import time

    def elapsed(n: int) -> float:
        text = "".join(
            f'if header :contains "subject" "s{i}" {{\n  keep;\n}}\n\n' for i in range(n)
        )
        script = st.parse_sieve(text)
        start = time.perf_counter()
        st.generate_sieve(script)
        return time.perf_counter() - start

    small, large = elapsed(100), elapsed(400)
    assert large < small * 8, f"4x the entries cost {large / small:.1f}x the time"


# ── The acceptance property ──


@pytest.mark.parametrize("path", CORPUS, ids=corpus_id)
def test_parse_then_save_with_no_edits_is_byte_identical(path: Path):
    """The bead's acceptance criterion.

    The old `generate(parse(x))` property could not express this: it compared
    two parsed structures, so anything the parser did not understand was absent
    from both sides and it passed vacuously. This compares BYTES, which is the
    only comparison a user can check by looking at their file.

    TWO SHAPES OF FILE ARE EXEMPT, and both deliberately. Neither can occur in
    the corpus, which is why this property holds over all of it:

      - A file with no `require` statement whose entries nonetheless need one.
        There is no `requires_source` to re-emit, so the generator takes the
        computed set and prepends a canonical `require [...];` — the save
        matches byte for byte except for that added line. Pinned by
        `test_a_file_missing_its_require_gains_one_and_that_is_correct`, which
        says why adding the line beats preserving the file.
      - The empty file, which comes back as `"\n"`. Pinned by
        `test_an_empty_script_saves_as_one_newline`.
    """
    text = path.read_text()
    assert st.generate_sieve(st.parse_sieve(text)) == text


def test_a_file_missing_its_require_gains_one_and_that_is_correct():
    """The one exception to "an unedited save is byte-identical".

    `fileinto` without `require ["fileinto"];` is not a file we are declining to
    reformat — it is invalid Sieve (RFC 5228 §2.10.5), and a real ManageSieve
    server refuses to install it. Preserving it faithfully would hand the user
    back a script their server will not take; adding the missing line makes it
    installable. So this is the one place the generator writes a byte nobody
    asked for, and it is strictly better than the alternative.

    Deliberately NOT a corpus fixture: adding one would make
    `test_parse_then_save_with_no_edits_is_byte_identical` fail, and the honest
    fix would be exempting it there rather than here — which is how a documented
    exception turns back into an undocumented hole.
    """
    text = 'if header :contains "subject" "box" {\n  fileinto "Box";\n}\n'
    script = st.parse_sieve(text)
    assert script.requires_source == "", "there is no require statement to re-emit"
    assert script.requires == [], "and none was declared"

    out = st.generate_sieve(script)
    assert out == 'require ["fileinto"];\n' + text
    # The rule itself still went out verbatim — the added line is the whole of
    # the difference, not a regeneration of everything below it.
    assert script.entries[0].source in out


# How much of the corpus the editing property below actually reaches. Its skip
# is honest — a fixture with no Rule has nothing to edit — but it is SILENT: the
# reason only shows under `-rs`, so the suite reads as covering 68 fixtures
# while the headline behaviour of this whole feature is verified on 25.
FIXTURES_WITH_A_RULE = 25


def test_the_editing_property_reaches_exactly_the_fixtures_it_claims_to():
    """Write the coverage cap down where someone will see it.

    43 of the 68 fixtures parse to no `Rule` at all — `vendor/` extension cases
    and deliberate raw fixtures that become `RawBlock`s by design — so
    `test_editing_one_rule_leaves_every_other_line_alone` skips them. Correct,
    and not something to remove. But a skip reason only surfaces under `-rs`,
    so nothing in a normal run says that this feature's headline behaviour is
    checked on a third of the corpus. This test is that sentence, in a place a
    reader lands on.

    IT IS NOT THE REGRESSION DETECTOR, and an earlier version of this docstring
    wrongly claimed it was. `test_sieve_transform.py::test_recognition_does_not_regress`
    already pins `(len(rules), len(raw_blocks))` for every one of the 68 in
    `RECOGNITION_CENSUS`, parametrized and strict. A fixture that stopped
    yielding Rules fails THERE first and by name, which is strictly more useful
    than watching this count slide 25 to 24. Expect the census to have named the
    culprit before anyone reads this.

    This pins a count, NOT a blessing. Several fixtures sit outside the
    recognised set for reasons someone owns — `vendor/bracket-comment.sieve`
    parses to a single whole-file `RawBlock` even after areyousievious-hr6 gave
    the parser bracketed comments, because its comments are INTERLEAVED with
    live code (`discard /* c */ ;`) rather than standing on their own lines, and
    the projection does not model that.

    Nor does with-Rule/without-Rule measure how much the byte-identical property
    constrains: forcing the verbatim path off fails 37 of the 68, and 22 of
    those 36 have no Rule at all. Half the RawBlock-only fixtures do bind the
    verbatim path, because their canonical rendering differs from their bytes.
    The two splits are unrelated; this one is about the EDITING property only.
    """
    assert len(CORPUS) == 68, "the corpus changed size — recount before editing the number below"
    with_a_rule = sorted(corpus_id(p) for p in CORPUS if st.parse_sieve(p.read_text()).rules)
    assert len(with_a_rule) == FIXTURES_WITH_A_RULE, (
        "the number of fixtures parsing to at least one Rule moved: "
        f"{len(with_a_rule)} now, {FIXTURES_WITH_A_RULE} pinned. If recognition IMPROVED, raise "
        "the number. If it REGRESSED, read test_recognition_does_not_regress first — it names the "
        f"fixture. Currently recognised: {with_a_rule}"
    )


@pytest.mark.parametrize("path", CORPUS, ids=corpus_id)
def test_editing_one_rule_leaves_every_other_line_alone(path: Path):
    """The point of the whole feature, measured: change one Rule and count how
    much of the file moved. Everything outside the edited rule must be
    untouched, so the diff is bounded by that one entry."""
    text = path.read_text()
    script = st.parse_sieve(text)
    rules = [i for i, e in enumerate(script.entries) if isinstance(e, st.Rule)]
    if not rules:
        pytest.skip("no Rule to edit in this fixture")
    target = rules[0]
    script.entries[target].name = script.entries[target].name + " (edited)"

    out = st.generate_sieve(script)
    # Assert on the ENTRIES, not on the head. Editing a rule puts the save on
    # the regenerating path, where `require` goes out canonically and may
    # legitimately differ from the bytes it was read from — asserting
    # `out.startswith(preamble + requires_source + ...)` would fail on every
    # fixture whose require line is not already in our house style, and the
    # tempting "fix" is to weaken the test rather than read it.
    for i, entry in enumerate(script.entries):
        if i == target:
            continue
        assert entry.source.strip() in out, f"entry {i} was rewritten and should not have been"
    assert script.preamble in out


def test_an_empty_script_saves_as_one_newline():
    """The second exception to "an unedited save is byte-identical".

    `""` in, `"\\n"` out. Both `generate`'s early return and its main path end
    `... or "\\n"`, so a script with nothing in it produces a single newline
    rather than an empty file. This is the OLD generator's behaviour, unchanged
    by spans — not a regression this branch introduced — and it is pinned here
    only so the exception list beside the acceptance property is complete
    rather than partial. No corpus fixture is empty (`CORPUS` filters on
    `st_size > 0`), so this cannot reach the parametrized property.
    """
    assert st.parse_sieve("").entries == []
    assert st.generate_sieve(st.parse_sieve("")) == "\n"


def test_an_empty_raw_block_last_does_not_leave_a_dangling_blank_line():
    """`generate`'s trailing-newline branch, which only the WIRE can reach.

    It is a no-op for anything the parser produces: `_canonical_span` returns
    `body.strip("\\n") + "\\n"`, so a regenerated last entry already leaves `out`
    ending in exactly one newline. But `RawBlockDTO.text` defaults to `""`, so
    `{"kind": "raw"}` is a valid entry on the wire, its canonical span is a
    bare `"\\n"`, and `_join` strips that to nothing — leaving the seam's blank
    line dangling at the end of the file.

    Measured rather than argued: deleting the branch changes this save's output
    from one trailing newline to two, and the whole suite stayed green either
    way. That silence is why this test exists.
    """
    script = st.SieveScript(
        entries=[
            st.Rule(name="A", actions=[st.Action(action_type="stop")]),
            st.RawBlock(text=""),
        ]
    )
    out = st.generate_sieve(script)
    assert out.endswith("}\n"), repr(out)
    assert not out.endswith("\n\n"), "the seam's blank line was left dangling"
