/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with IMAP credentials.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Status
         * @description Report whether this request carries a live session.
         *
         *     Never 401s — an unauthenticated caller is the answer, not an error, which
         *     is why this takes `get_optional_session` rather than `get_session`.
         */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_api_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scripts */
        get: operations["list_scripts_api_scripts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Script
         * @description Import a .sieve file as a new script.
         *
         *     ponytail: sync handler so FastAPI runs it in a threadpool — the slow
         *     ManageSieve PUT no longer blocks the event loop (Perf C1 / Fwk C-1).
         */
        post: operations["import_script_api_scripts_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Script
         * @description Get script parsed as JSON rules.
         */
        get: operations["get_script_api_scripts__name__get"];
        /**
         * Save Script
         * @description Save script from JSON rules (generates Sieve).
         */
        put: operations["save_script_api_scripts__name__put"];
        post?: never;
        /** Delete Script */
        delete: operations["delete_script_api_scripts__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{name}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Script */
        post: operations["activate_script_api_scripts__name__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{name}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Script
         * @description Download script as a .sieve file.
         */
        get: operations["export_script_api_scripts__name__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{name}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Script Raw
         * @description Get raw Sieve text.
         */
        get: operations["get_script_raw_api_scripts__name__raw_get"];
        /**
         * Save Script Raw
         * @description Save raw Sieve text directly.
         */
        put: operations["save_script_raw_api_scripts__name__raw_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. No auth, no dependencies, no I/O.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Frontend
         * @description Serve Svelte build files, fallback to index.html for SPA routing.
         */
        get: operations["serve_frontend__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionDTO */
        ActionDTO: {
            /**
             * Argument
             * @default
             */
            argument: string;
            /** Type */
            type: string;
        };
        /** AuthStatusResponse */
        AuthStatusResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Host */
            host?: string | null;
            /** Username */
            username?: string | null;
        };
        /** Body_import_script_api_scripts_import_post */
        Body_import_script_api_scripts_import_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
        };
        /** ConditionDTO */
        ConditionDTO: {
            /**
             * Address Part
             * @default
             * @enum {string}
             */
            address_part: "" | "all" | "localpart" | "domain";
            /**
             * Address Test
             * @default false
             */
            address_test: boolean;
            /**
             * Comparator
             * @default
             */
            comparator: string;
            /** Header */
            header: string;
            /** Match Type */
            match_type: string;
            /**
             * Negate
             * @default false
             */
            negate: boolean;
            /**
             * Value
             * @default
             */
            value: string;
        };
        /** CreateFolderRequest */
        CreateFolderRequest: {
            /** Name */
            name: string;
        };
        /** FolderListItem */
        FolderListItem: {
            /** Delimiter */
            delimiter: string;
            /** Flags */
            flags?: string[];
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Host */
            host: string;
            /** Password */
            password: string;
            /**
             * Port Imap
             * @default 993
             */
            port_imap: number;
            /**
             * Port Sieve
             * @default 4190
             */
            port_sieve: number;
            /** Username */
            username: string;
        };
        /**
         * OkResponse
         * @description Generic mutating-endpoint response. `name` / `sieve` are populated
         *     by individual routes; `response_model_exclude_none=True` keeps the
         *     payload minimal.
         */
        OkResponse: {
            /** Name */
            name?: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Sieve */
            sieve?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * RawBlockDTO
         * @description A Raw Block entry on the wire — Sieve the parser didn't recognise.
         */
        RawBlockDTO: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "raw";
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * RuleDTO
         * @description A Rule entry on the wire.
         *
         *     Carries no `id` — identity is view state (docs/adr/0001-identity-is-view-state.md).
         *     Clients mint their own render keys and strip them before saving.
         */
        RuleDTO: {
            /** Actions */
            actions?: components["schemas"]["ActionDTO"][];
            /** Conditions */
            conditions?: components["schemas"]["ConditionDTO"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rule";
            /**
             * Match
             * @default anyof
             */
            match: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /**
         * SaveRawRequest
         * @description `content` is required and non-empty: an empty raw save destroys the
         *     user's script, and the one observed way to send one was a bug, not an
         *     intent (areyousievious-8fg.20). Clearing a script is expressed by
         *     deleting it, not by overwriting it with nothing.
         */
        SaveRawRequest: {
            /** Content */
            content: string;
        };
        /**
         * SaveScriptRequest
         * @description Typed save body. Every entry is parsed against its DTO and an unknown
         *     field anywhere in the tree is a hard 422.
         *
         *     `entries` is one ordered sequence — position is the evaluation order. It
         *     replaced parallel rules/raw_blocks/order arrays, where an order array that
         *     omitted one of its own rules caused that rule to be silently dropped.
         */
        SaveScriptRequest: {
            /** Entries */
            entries?: (components["schemas"]["RuleDTO"] | components["schemas"]["RawBlockDTO"])[];
            /** Requires */
            requires?: string[];
        };
        /** ScriptListItem */
        ScriptListItem: {
            /** Active */
            active: boolean;
            /** Name */
            name: string;
        };
        /** ScriptRawResponse */
        ScriptRawResponse: {
            /** Content */
            content: string;
            /** Name */
            name: string;
        };
        /**
         * ScriptResponse
         * @description GET /api/scripts/{name} — mirrors what `script_to_json` emits.
         */
        ScriptResponse: {
            /** Entries */
            entries?: (components["schemas"]["RuleDTO"] | components["schemas"]["RawBlockDTO"])[];
            /** Requires */
            requires?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    list_folders_api_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderListItem"][];
                };
            };
        };
    };
    create_folder_api_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scripts_api_scripts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptListItem"][];
                };
            };
        };
    };
    import_script_api_scripts_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_script_api_scripts_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_script_api_scripts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_script_api_scripts__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveScriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_script_api_scripts__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_script_api_scripts__name__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_script_api_scripts__name__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_script_raw_api_scripts__name__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptRawResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_script_raw_api_scripts__name__raw_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRawRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    serve_frontend__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
